version: '3.8'

services:
  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_PLAINTEXT: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  # PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"

  # Producer
  producer:
    image: bronzzza/telemetry-producer-multistage:latest
    ports:
      - "8080:8080"
    container_name: telemetry-producer
    environment:
      KAFKA_BROKER_URL: kafka:9093
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_TOPIC: device_data
      TELEMETRY_PRODUCER_INTERVAL: 15000
    depends_on:
      - kafka
    command: >
      --app.deviceId=drone123
      --app.deviceName=droneX
      --app.startLatitude=50.4501
      --app.startLongitude=30.5234
      --app.endLatitude=55.7558
      --app.endLongitude=37.6173
      --app.speed=0.14

  # Consumer
  consumer:
    image: bronzzza/telemetry-consumer-pom:latest
    ports:
      - "8081:8081"
    container_name: telemetry-consumer
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BROKER_URL: kafka:9093
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telemetry
      SPRING_DATASOURCE_USERNAME: telemetry
      SPRING_DATASOURCE_PASSWORD: telemetry
    depends_on:
      - kafka
      - db

  # UI
  drone-tracker:
    image: bronzzza/drone-tracker:latest
    container_name: drone-tracker
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://telemetry-consumer:8081/api/telemetry/device/location
      - REACT_APP_DEVICE_ID=drone123
    depends_on:
      - consumer