spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: load-test-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 1000
      session-timeout-ms: 15000
      max-poll-records: 500
      max-poll-interval-ms: 300000
      fetch-max-bytes: 10485760
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      concurrency: 3